[package]
name = "zed_objc"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/objc.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }
zed_extension_api = "0.7.0"
