id = "objc"
name = "Objective-C"
description = "Objective-C support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Zed Community"]
repository = "https://github.com/nipsarejusttittips/zed-objc"

[grammars.objc]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-objc"
commit = "181a81b8f23a2d593e7ab4259981f50122909fda"
